name: semantic-release

on:
  push:
    branches:
      - development
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run automated release process with semantic-release
        if: github.event_name == 'push'
        uses: cycjimmy/semantic-release-action@v2
        with:
          branch: development
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            @semantic-release/exec
        env:
          GH_TOKEN: ${{ secrets.COACHHUB_GITHUB_PACKAGE_TOKEN }}
          NPM_TOKEN: ${{ secrets.COACHHUB_GITHUB_PACKAGE_TOKEN }}
